[features]
seeds = false
[programs.devnet]
gifportalbackend = "338BZQTraQYe4yLfDa6Cb4WMACeF3ccv3umBKTER7R96"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
## Apple
wallet = "/users/philipp/.config/solana/id.json"
## windows
# wallet = "/home/philipp/.config/solana/id.json"

[scripts]
test = "node tests/gifportalbackend.js"
